# Generated by Django 3.1.5 on 2021-03-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210316_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(default='https://static.productionready.io/images/smiley-cyrus.jpg'),
        ),
    ]
