version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=todoDatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Xyz@av153k
    logging: 
      options: 
        max-size: 10m
        max-file: "3"
    ports: 
      - '5432:5432'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes: 
      - .:/web
    depends_on:
      - db