# Generated by Django 3.1.5 on 2021-11-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(default='https://static.productionready.io/images/smiley-cyrus.jpg'),
        ),
    ]
